//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmBookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIETSACH
    {
        public string MaTG { get; set; }
        public string MaSach { get; set; }
        public string VaiTro { get; set; }
        public Nullable<int> ViTri { get; set; }
    
        public virtual SACH SACH { get; set; }
        public virtual TAGGIA TAGGIA { get; set; }
    }
}
